can't call `expand`. heeeeeelp
`tsc` said:

src/App.tsx:3:24 - error TS7016: Could not find a declaration file for module 'emmet'. '/home/tbm/dev/ts/learn-react/02-learn-emmet/node_modules/emmet/dist/emmet.es.js' implicitly has an 'any' type.
  There are types at '/home/tbm/dev/ts/learn-react/02-learn-emmet/node_modules/emmet/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'emmet' library may need to update its package.json or typings.

3 import * as emmet from 'emmet';
                         ~~~~~~~

Found 1 error in src/App.tsx:3